### ISSUE TITLE
Basic Thermostat in UK

### ISSUE THREAD

**Issue by schweppy** [ankurp/homebridge-pi-thermostat#4]
Hi

I'm in the UK with a basic thermostat that has no fan or cooling.

Is it possible to run this plugin without the lines for fan and cooling in the config.json as I only need a basic temperature sensor and relay to switch on the heating?

Thanks

**Comment by ankurp** [comment]
@schweppy  Yes this can work with any thermostat as it will basically will do nothing even for cool. All you need to do is connect the Heating and Power wire and skip the Fan and the Cooling wires.

**Comment by ankurp** [comment]
Let me know if you run into any issue and can help.
